import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Login',
    description: 'Generated by Nika ',
  }
  
const AuthLayout = ({ children }:{ children:React.ReactNode}) => {
    return (
        <div className="bg-red-500 h-full">
            {children}
        </div>
    )
    }

export default AuthLayout;